import HTTPS from '@/configs/api/base';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import styles from '@/utils/assets/styles/Home.module.css';
import { Container, Divider, Text } from '@nextui-org/react';
import FileInput from '@/core/components/drapfile';
import { Data, Tour } from '@/core/interfaces/tour';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="py-3 text-center text-yellow-300"></div>
        </div>
    );
}
