import HTTPS from '@/configs/api/base';
import Head from 'next/head';
import { useEffect } from 'react';

import styles from '@/utils/assets/styles/Home.module.css';
import { Container, Text } from '@nextui-org/react';
import FileInput from '@/core/components/drapfile';

export default function Home() {
    useEffect(() => {
        HTTPS.get('/blog').then((res) => console.log(res.data));
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="py-3 text-center text-yellow-300">
                <Text h3>Home</Text>
                <Container>
                    <div className="flex justify-center p-3">
                        <FileInput />
                    </div>
                </Container>
            </div>
        </div>
    );
}
