import HTTPS from '@/configs/api/base';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import styles from '@/utils/assets/styles/Home.module.css';
import Layouts from '@/core/components/layouts';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home Pages</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="py-3 text-center ">hello world</div>
        </div>
    );
}
Home.getLayout = function getLayout(page): JSX.Element {
    return <Layouts>{page}</Layouts>;
};
